### ISSUE TITLE
A lot of crash using tapdaq 2.5.1

### ISSUE THREAD

**Issue by ayublin** [tapdaq/tapdaq-android-sdk#2]
Hello, I am getting a lot of crash from my users using the latest version of tapdaq SDK, here it is:

http://prntscr.com/c88mmo

I would really appreciate a quick fix since it is affecting around 50 users daily.

Thanks!

**Comment by rdominic** [comment]
Hi,

Thanks for the report. 2.5.2 is now available with a fix for this.

Dominic
