### ISSUE TITLE
AppCompatActivity

### ISSUE THREAD

**Issue by erebar** [tapdaq/tapdaq-android-sdk#3]
Hello I'm getting a RuntimeException on android related to the 3.1 sdk. "java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity."

I'm using cocos2dx for my app so the main activity extends Cocos2dxActivity. I've seen in the sample that the main activity extends TMAppCompatActivity and that extends android.support.v7.app.AppCompatActivity, is this a requirement of your sdk? Any way to work around it?

Thanks

**Comment by rdominic** [comment]
Hi Erebar,

Thanks for getting in touch, the dependency on AppCompat will be removed in v3.2.0 which will be available shortly. However this will raise the minimum API level to 11 (rather than 9), I hope this isn't a problem for you.

Dominic

**Comment by erebar** [comment]
Hi Dominic, no that's not a problem, thanks. Ill be looking for the new release.

**Comment by rdominic** [comment]
I've just pushed the release 3.2.0. Please let me know how it goes.

You don't have to use TMAppCompatActivity (now called TMLifecycleActivity), but you should implement the lifecycle events in all of your activities if you're using our mediation services. Described here https://github.com/tapdaq/tapdaq-android-sdk/wiki/Mediation

Thanks,
Dominic

**Comment by erebar** [comment]
It's working for the most part, I'm not getting the exception anymore, however there's a problem, at least on my side: 
I'm using URL promotions to test that all is working, but I'm only getting the interstitial when I use the TMAdAvailabilityListener and only for the 1st interstitial. All the other interstitials that I call with showInterstitial return me a "onAdFailedToLoad Unknown Error" on the TMAdListener. 

Thanks,
Eric

**Comment by rdominic** [comment]
Hi Eric,

Are you using Ad Mob for Mediation? I think thats where that error is coming from.

If you like we can move this to a Skype or Google Hangouts message chat so I can look into your account if necessary. My contact email for both is dom.roberts@tapdaq.com

Thanks,
Dominic

**Comment by erebar** [comment]
Hi Dominic, I've send you a request on Skype. I'm not using ad mob, only cross promotion.
