### ISSUE TITLE
App crashing

### ISSUE THREAD

**Issue by yourtushki** [tapdaq/tapdaq-android-sdk#4]
Not sure if there is an issue with my device but this happens when I try to implement tapdaq sdk

![error](https://cloud.githubusercontent.com/assets/24815964/22797594/d910b64a-ef24-11e6-8a1a-9a36671e5bd4.png)

Android Version 4.4.2
Device Moto E

Also you should update Quick start page for arguments of this function
Tapdaq.getInstance().initialize(this, "<APP_ID>", "<CLIENT_KEY>", new TMInitListener(), config);
to
Tapdaq.getInstance().initialize(this, "<APP_ID>", "<CLIENT_KEY>", config, new TMInitListener());

Please ignore if I misunderstood anything. 

Thank you

**Comment by yourtushki** [comment]
Ok I figured it out. There was no sim card in that phone so null for TMCarrier and parseInt gave that error. It worked fine when I added sim card.

**Comment by rdominic** [comment]
Hi, Thanks for getting in touch. You're absolutely right. I'll update the docs and will fix the crash in our release next week.

Thanks,
Dominic

**Comment by rdominic** [comment]
Hi @yourtushki 

Sorry for the delayed reply, a fix for this was released with version 4.3.0. Please update the latest version.

Thanks,
Dominic
